-- Relève — seed content (§12). GENERATED by scripts/gen-seed.ts.
-- Do not edit by hand: edit src/content/*.json and re-run `pnpm gen:seed`.
-- Idempotent: safe to re-run. Content is authoritative and fully replaced.

BEGIN;

-- Wipe seeded content (routine_steps cascade from routines).
TRUNCATE routines RESTART IDENTITY CASCADE;
TRUNCATE articles RESTART IDENTITY CASCADE;

-- debout
WITH r AS (
  INSERT INTO routines (slug, title, zone, duration_s, summary, accent, sort_order)
  VALUES ('debout', 'Debout', 'general', 180, 'La pause de référence. Trois minutes, toutes les trente minutes.', 'lime', 1)
  RETURNING id
)
INSERT INTO routine_steps (routine_id, position, name, duration_s, cue, figure_key)
VALUES
  ((SELECT id FROM r), 1, 'Marche', 30, 'Lève-toi et marche. Sors de la pièce si tu peux.', 'marche'),
  ((SELECT id FROM r), 2, 'Extension debout', 30, 'Mains dans le bas du dos, ouvre la poitrine, regarde vers le plafond. Doucement.', 'extension-debout'),
  ((SELECT id FROM r), 3, 'Fente basse — droite', 30, 'Un grand pas en avant, genou arrière tendu. Pousse la hanche arrière vers l''avant.', 'fente'),
  ((SELECT id FROM r), 4, 'Fente basse — gauche', 30, 'Même chose de l''autre côté. Le bassin reste droit.', 'fente'),
  ((SELECT id FROM r), 5, 'Regard au loin', 30, 'Cherche le point le plus lointain visible, et cligne lentement dix fois.', 'loin-pres'),
  ((SELECT id FROM r), 6, 'Marche', 30, 'Retour au poste en marchant. Rien ne presse.', 'marche');

-- hanches
WITH r AS (
  INSERT INTO routines (slug, title, zone, duration_s, summary, accent, sort_order)
  VALUES ('hanches', 'Hanches', 'hanches', 240, 'Ce qui se raccourcit vraiment quand on reste assis huit heures.', 'blush', 2)
  RETURNING id
)
INSERT INTO routine_steps (routine_id, position, name, duration_s, cue, figure_key)
VALUES
  ((SELECT id FROM r), 1, 'Fente basse — droite', 40, 'Genou arrière au sol ou tendu. Rentre le bassin, puis avance.', 'fente'),
  ((SELECT id FROM r), 2, 'Fente basse — gauche', 40, 'Même chose de l''autre côté.', 'fente'),
  ((SELECT id FROM r), 3, 'Figure 4 assise — droite', 40, 'Cheville droite sur le genou gauche, penche le buste, dos droit.', 'figure4-assise'),
  ((SELECT id FROM r), 4, 'Figure 4 assise — gauche', 40, 'Même chose de l''autre côté.', 'figure4-assise'),
  ((SELECT id FROM r), 5, 'Ischios — droite', 30, 'Talon sur une chaise basse, jambe tendue, penche depuis les hanches.', 'ischios'),
  ((SELECT id FROM r), 6, 'Ischios — gauche', 30, 'Même chose de l''autre côté.', 'ischios'),
  ((SELECT id FROM r), 7, 'Balancement de hanche', 20, 'Debout, jambe libre, balance d''avant en arrière. Amplitude confortable.', 'balancement-hanche');

-- lombaires
WITH r AS (
  INSERT INTO routines (slug, title, zone, duration_s, summary, accent, sort_order)
  VALUES ('lombaires', 'Lombaires', 'lombaires', 240, 'Le bas du dos n''a pas besoin d''être renforcé après huit heures assis. Il a besoin de bouger.', 'sage', 3)
  RETURNING id
)
INSERT INTO routine_steps (routine_id, position, name, duration_s, cue, figure_key)
VALUES
  ((SELECT id FROM r), 1, 'Chat-vache debout', 40, 'Mains sur les cuisses. Arrondis le dos, puis creuse-le, au rythme de ta respiration.', 'chat-vache'),
  ((SELECT id FROM r), 2, 'Inclinaison latérale — droite', 30, 'Un bras au-dessus de la tête, penche du côté opposé. Respire dans les côtes.', 'inclinaison-laterale'),
  ((SELECT id FROM r), 3, 'Inclinaison latérale — gauche', 30, 'Même chose de l''autre côté.', 'inclinaison-laterale'),
  ((SELECT id FROM r), 4, 'Rotation assise — droite', 30, 'Pieds au sol, tourne le buste, attrape le dossier. Le regard suit.', 'rotation-assise'),
  ((SELECT id FROM r), 5, 'Rotation assise — gauche', 30, 'Même chose de l''autre côté.', 'rotation-assise'),
  ((SELECT id FROM r), 6, 'Extension debout', 40, 'Mains dans le bas du dos, ouvre vers l''arrière. Petite amplitude, sans forcer.', 'extension-debout'),
  ((SELECT id FROM r), 7, 'Bascule du bassin', 40, 'Debout, bascule le bassin d''avant en arrière, comme un seau qu''on vide.', 'bascule-bassin');

-- nuque
WITH r AS (
  INSERT INTO routines (slug, title, zone, duration_s, summary, accent, sort_order)
  VALUES ('nuque', 'Nuque & trapèzes', 'nuque', 180, 'Trois minutes sur ce qui prend cher quand l''écran est trop bas.', 'sky', 4)
  RETURNING id
)
INSERT INTO routine_steps (routine_id, position, name, duration_s, cue, figure_key)
VALUES
  ((SELECT id FROM r), 1, 'Menton rentré', 30, 'Recule le menton comme pour faire un double menton. Tiens 5 s, relâche, recommence.', 'menton-rentre'),
  ((SELECT id FROM r), 2, 'Inclinaison — droite', 30, 'Oreille vers l''épaule, la main opposée relâche. Ne tire pas.', 'nuque-laterale'),
  ((SELECT id FROM r), 3, 'Inclinaison — gauche', 30, 'Même chose de l''autre côté.', 'nuque-laterale'),
  ((SELECT id FROM r), 4, 'Rotation lente', 30, 'Tourne la tête d''un côté puis de l''autre, comme si tu suivais un horizon.', 'nuque-rotation'),
  ((SELECT id FROM r), 5, 'Haussements d''épaules', 30, 'Monte les épaules vers les oreilles, tiens 3 s, laisse tomber d''un coup.', 'haussement-epaules'),
  ((SELECT id FROM r), 6, 'Ouverture à l''encadrement', 30, 'Avant-bras contre un montant de porte, avance d''un pas. Poitrine ouverte.', 'encadrement-porte');

-- dos
WITH r AS (
  INSERT INTO routines (slug, title, zone, duration_s, summary, accent, sort_order)
  VALUES ('dos', 'Haut du dos', 'dos', 240, 'La zone que le renforcement protège le mieux, d''après les essais.', 'navy', 5)
  RETURNING id
)
INSERT INTO routine_steps (routine_id, position, name, duration_s, cue, figure_key)
VALUES
  ((SELECT id FROM r), 1, 'Serrage d''omoplates', 40, 'Serre les omoplates l''une vers l''autre, tiens 5 s, relâche.', 'omoplates'),
  ((SELECT id FROM r), 2, 'Cercles de bras', 30, 'Grands cercles vers l''arrière, lentement, amplitude maximale.', 'cercle-bras'),
  ((SELECT id FROM r), 3, 'Ouverture pectorale', 40, 'Mains croisées derrière la tête, ouvre les coudes vers l''extérieur.', 'ouverture-pectorale'),
  ((SELECT id FROM r), 4, 'Rotation externe', 40, 'Coudes au corps, les avant-bras s''écartent comme deux portes.', 'rotation-externe'),
  ((SELECT id FROM r), 5, 'Extension sur chaise', 40, 'Assis, mains derrière la tête, passe le haut du dos par-dessus le dossier.', 'extension-chaise'),
  ((SELECT id FROM r), 6, 'Tirage à vide', 50, 'Bras tendus devant, tire les coudes vers l''arrière comme sur une machine.', 'tirage-vide');

-- yeux
WITH r AS (
  INSERT INTO routines (slug, title, zone, duration_s, summary, accent, sort_order)
  VALUES ('yeux', 'Yeux', 'yeux', 60, 'Une minute. Le clignement compte plus que le chronomètre.', 'sun', 6)
  RETURNING id
)
INSERT INTO routine_steps (routine_id, position, name, duration_s, cue, figure_key)
VALUES
  ((SELECT id FROM r), 1, 'Clignements lents', 20, 'Vingt clignements francs, paupières complètement fermées à chaque fois.', 'clignement'),
  ((SELECT id FROM r), 2, 'Loin, près', 20, 'Fixe le point le plus lointain 3 s, puis ton pouce à 20 cm 3 s. Alterne.', 'loin-pres'),
  ((SELECT id FROM r), 3, 'Paumes', 20, 'Paumes en coupe sur les yeux ouverts, sans appuyer. Noir complet, respire.', 'paumes');

-- reveil
WITH r AS (
  INSERT INTO routines (slug, title, zone, duration_s, summary, accent, sort_order)
  VALUES ('reveil', 'Réveil', 'general', 300, 'Cinq minutes pour démarrer la journée avant de s''asseoir.', 'peach', 7)
  RETURNING id
)
INSERT INTO routine_steps (routine_id, position, name, duration_s, cue, figure_key)
VALUES
  ((SELECT id FROM r), 1, 'Marche sur place', 40, 'Genoux hauts, bras qui accompagnent. Monte en température.', 'marche'),
  ((SELECT id FROM r), 2, 'Cercles de bras', 40, 'Vers l''arrière, amplitude maximale, épaules relâchées.', 'cercle-bras'),
  ((SELECT id FROM r), 3, 'Chat-vache debout', 40, 'Mains sur les cuisses, arrondis puis creuse.', 'chat-vache'),
  ((SELECT id FROM r), 4, 'Fente basse — droite', 40, 'Pousse la hanche arrière vers l''avant.', 'fente'),
  ((SELECT id FROM r), 5, 'Fente basse — gauche', 40, 'Même chose de l''autre côté.', 'fente'),
  ((SELECT id FROM r), 6, 'Inclinaison latérale — droite', 30, 'Bras au-dessus de la tête, respire dans les côtes.', 'inclinaison-laterale'),
  ((SELECT id FROM r), 7, 'Inclinaison latérale — gauche', 30, 'Même chose de l''autre côté.', 'inclinaison-laterale'),
  ((SELECT id FROM r), 8, 'Menton rentré', 20, 'Recule le menton, tiens 5 s, relâche.', 'menton-rentre'),
  ((SELECT id FROM r), 9, 'Respiration', 20, 'Quatre respirations : inspire sur 4 temps, expire sur 6.', 'respiration');

-- pourquoi-30-minutes
INSERT INTO articles (slug, title, dek, body_md, tag, evidence, read_min, source_label, source_url, sort_order)
VALUES ('pourquoi-30-minutes', 'Pourquoi trente minutes', 'Le seul intervalle qui a été testé dose par dose, et ce qu’il change.', 'La plupart des conseils sur les pauses sont des chiffres ronds que personne n''a vérifiés. Celui-ci fait exception.

Une équipe de Columbia a fait asseoir onze adultes pendant huit heures en laboratoire, et a comparé cinq protocoles : une minute de marche toutes les trente minutes, une minute toutes les heures, cinq minutes toutes les trente minutes, cinq minutes toutes les heures, et rien du tout.

Un seul protocole a amélioré à la fois la glycémie et la tension artérielle : **cinq minutes de marche toutes les trente minutes**. Le pic de sucre après le repas baissait de 58 %, et la tension de 4 à 5 mmHg — une baisse que l''auteur principal compare à six mois d''entraînement quotidien. Une minute toutes les trente minutes donnait un effet modeste, sur la glycémie seulement.

Ce qu''il faut garder en tête : onze participants, en laboratoire, sur des marqueurs intermédiaires. C''est une démonstration de mécanisme, pas une étude de mortalité. Mais c''est le seul essai qui a comparé les doses entre elles, et c''est pour ça que trente minutes est l''intervalle par défaut de cette app.

Si trente minutes ne tient pas dans tes journées, quarante-cinq vaut mieux que rien. L''intervalle que tu respectes bat toujours celui que tu ignores.', 'preuve', 'solide', 3, 'Columbia University Irving Medical Center, 2023', 'https://www.cuimc.columbia.edu/news/rx-prolonged-sitting-five-minute-stroll-every-half-hour', 1);

-- vingt-vingt-vingt
INSERT INTO articles (slug, title, dek, body_md, tag, evidence, read_min, source_label, source_url, sort_order)
VALUES ('vingt-vingt-vingt', 'Le 20-20-20 n’a jamais été prouvé', 'La règle la plus répétée du travail sur écran, et ce qui marche à la place.', 'Toutes les vingt minutes, regarder à vingt pieds pendant vingt secondes. La règle est attribuée à l''optométriste américain Jeffrey Anshel, elle est reprise partout, et elle n''a jamais été validée.

Une étude contrôlée l''a testée directement : trente participants, une tâche de lecture de quarante minutes sur tablette, avec des pauses programmées toutes les cinq, dix, vingt ou quarante minutes. Résultat : aucun effet significatif sur les symptômes oculaires (p = 0,70), sur la vitesse de lecture (p = 0,93), ni sur la précision (p = 0,55). Les auteurs concluent que des pauses de vingt secondes ne tiennent pas comme intervention.

Ça ne veut pas dire que la fatigue visuelle est imaginaire. Le mécanisme est réel : devant un écran, le taux de clignement s''effondre, le film lacrymal s''évapore, et l''œil sèche. Mais la variable utile n''est pas le chronomètre.

Ce qui marche, dans l''ordre : **baisser l''écran** sous la ligne des yeux, ce qui fait tomber la paupière et réduit la surface exposée ; **écarter la ventilation** ou la clim qui souffle vers le visage ; et **cligner franchement**, paupières complètement fermées, quand tu y penses.

Le rappel « yeux » existe dans cette app, mais il est désactivé par défaut. C''est volontaire.', 'preuve', 'non-demontree', 3, '« 20-20-20 Rule: Are These Numbers Justified? », PubMed 36473088', 'https://pubmed.ncbi.nlm.nih.gov/36473088/', 2);

-- debout-nest-pas-actif
INSERT INTO articles (slug, title, dek, body_md, tag, evidence, read_min, source_label, source_url, sort_order)
VALUES ('debout-nest-pas-actif', 'Debout n’est pas actif', 'Ce que 83 000 porteurs d’accéléromètre ont appris sur le bureau assis-debout.', 'Le bureau assis-debout s''est vendu comme l''antidote à la sédentarité. Les données ne suivent pas.

L''UK Biobank a suivi 83 013 adultes sans maladie cardiaque au départ, pendant sept à huit ans, avec un accéléromètre au poignet — donc du temps debout mesuré, pas déclaré. Rester debout plus longtemps n''a pas amélioré le risque cardiovasculaire. Pire, le temps debout prolongé était associé à davantage de troubles circulatoires : varices, thrombose veineuse.

Au-delà de dix heures assis par jour, en revanche, les deux risques montent. Le seuil compte, et il inclut le canapé du soir, pas seulement le bureau.

La conclusion des chercheurs tient en une phrase : rester debout trop longtemps ne compense pas un mode de vie sédentaire. Ce qui compte, c''est le **changement de position** et la marche, pas la station verticale.

Concrètement : si tu as un bureau réglable, sers-t''en pour alterner, pas pour tenir huit heures debout. Et alterner ne remplace pas de sortir marcher.', 'preuve', 'solide', 3, 'University of Sydney / International Journal of Epidemiology, 2024', 'https://www.sydney.edu.au/news-opinion/news/2024/10/17/standing-more-may-not-reduce-cardiovascular-disease-risk--could-.html', 3);

-- ce-que-les-pauses-changent
INSERT INTO articles (slug, title, dek, body_md, tag, evidence, read_min, source_label, source_url, sort_order)
VALUES ('ce-que-les-pauses-changent', 'Ce que les pauses changent vraiment', 'Elles rechargent, elles ne rendent pas plus performant. La nuance a son importance.', 'Une méta-analyse de 2022 a rassemblé 22 échantillons et 2 335 participants pour mesurer ce que font les micro-pauses.

Sur le bien-être, l''effet est net et constant : plus de vigueur (d = 0,36), moins de fatigue (d = 0,35), quel que soit le contexte.

Sur la performance, c''est autre chose. L''effet global est petit et **non significatif** (d = 0,16). Il devient positif sur les tâches administratives et créatives, et reste quasi nul sur les tâches cognitivement exigeantes — celles-là demandent des pauses de plus de dix minutes pour en tirer quoi que ce soit.

Autrement dit : une pause de trois minutes ne va pas te rendre plus intelligent sur un problème difficile. Elle va te faire finir la journée moins cassé. C''est déjà la seule promesse que cette app fait.

C''est aussi pour ça qu''il n''y a pas de mode « concentration » ici. Si tu es dans un problème dur, ignore le rappel et lève-toi au suivant. Le système est fait pour être ignoré de temps en temps sans culpabilité.', 'preuve', 'partielle', 3, '« Give me a break! », PLOS One, 2022', 'https://journals.plos.org/plosone/article?id=10.1371%2Fjournal.pone.0272460', 4);

-- muscler-le-haut-du-dos
INSERT INTO articles (slug, title, dek, body_md, tag, evidence, read_min, source_label, source_url, sort_order)
VALUES ('muscler-le-haut-du-dos', 'Le renforcement divise le risque par deux', 'L’intervention la plus rentable contre les douleurs de nuque, et elle n’est pas dans cette app.', 'Une méta-analyse publiée en 2023 a réuni cinq essais randomisés et 1 722 participants pour une question simple : est-ce que faire de l''exercice évite d''avoir mal à la nuque ?

Réponse : les groupes qui s''entraînaient avaient environ **deux fois moins de risque** de développer une cervicalgie (rapport de cotes 0,49 ; intervalle de confiance 0,31–0,76). Sur mille personnes et douze mois, cela représente environ 127 cas évités. Il faut faire s''entraîner huit personnes pour en épargner une. Certitude modérée.

Ce qui marchait dans les essais : renforcement de la nuque et des épaules, pauses actives, travail de contrôle moteur, activité physique générale. Aucun format n''écrase les autres — celui que tu suivras est le bon.

Et c''est le point important : trois minutes de mobilité toutes les trente minutes ne remplacent pas dix minutes de tirage horizontal deux fois par semaine. Si tu vas déjà à la salle, ajoute du travail de haut du dos à ce que tu fais. C''est là que se joue l''essentiel, pas dans une notification.', 'pratique', 'solide', 3, 'Journal of Orthopaedic & Sports Physical Therapy, 2023', 'https://www.jospt.org/doi/10.2519/jospt.2023.12063', 5);

-- regler-son-poste
INSERT INTO articles (slug, title, dek, body_md, tag, evidence, read_min, source_label, source_url, sort_order)
VALUES ('regler-son-poste', 'Régler son poste une fois pour toutes', 'Sept mesures, dix minutes, zéro euro. Le meilleur rapport effort/effet de la liste.', 'Avant toute app, il y a le poste. Les repères de l''INRS, à appliquer une fois :

- **Distance œil–écran** : 50 à 70 cm, soit environ la longueur du bras.
- **Hauteur** : le haut de l''écran au niveau des yeux ou légèrement en dessous. Jamais au-dessus.
- **Clavier** : à 10 à 15 cm du bord du bureau, pour que les avant-bras reposent.
- **Genoux** : angle droit ou légèrement ouvert, cuisses horizontales.
- **Fenêtres** : écran perpendiculaire à la fenêtre, à plus de 150 cm.
- **Éclairage** : 300 à 500 lux sur un écran à fond clair, température 3000 à 4000 K.
- **Pauses actives** : idéalement toutes les 30 minutes.

Une note pour les yeux secs en particulier : baisser l''écran fait tomber la paupière plus bas, réduit la surface de l''œil exposée à l''air, et donc l''évaporation. C''est le réglage qui a le plus d''effet, il est gratuit, et il prend trente secondes.

L''autre coupable classique n''est pas l''écran mais la ventilation : une bouche de clim qui souffle vers le visage assèche l''œil bien plus vite que huit heures de tableur.', 'reglage', 'partielle', 2, 'INRS — Travail sur écran, prévention des risques', 'https://www.inrs.fr/risques/travail-ecran/prevention-risques.html', 6);

COMMIT;
