import type { AccentKey, Article, Routine, Zone } from '@/lib/types'
import routinesJson from './routines.json'
import articlesJson from './articles.json'

/**
 * Local copy of the seeded content (§12). Used as the offline fallback on the
 * very first launch, before /api/routines and /api/articles have ever answered.
 * The database is the source of truth once online; this file must stay in sync
 * with db/002_seed_content.sql (both are generated by scripts/gen-seed.ts).
 */

export const LOCAL_ROUTINES = routinesJson as Routine[]
export const LOCAL_ARTICLES = articlesJson as Article[]

export interface ZoneMeta {
  zone: Zone
  label: string
  /** Representative figure + tone for the zone card. */
  figureKey: string
  tone: AccentKey
}

/** §11.1 — the six browse-by-zone cards, in display order. */
export const ZONES: ZoneMeta[] = [
  { zone: 'general', label: 'Général', figureKey: 'marche', tone: 'lime' },
  { zone: 'hanches', label: 'Hanches', figureKey: 'fente', tone: 'blush' },
  { zone: 'lombaires', label: 'Lombaires', figureKey: 'chat-vache', tone: 'sage' },
  { zone: 'nuque', label: 'Nuque', figureKey: 'menton-rentre', tone: 'sky' },
  { zone: 'dos', label: 'Haut du dos', figureKey: 'omoplates', tone: 'navy' },
  { zone: 'yeux', label: 'Yeux', figureKey: 'clignement', tone: 'sun' },
]

export const ZONE_LABEL: Record<Zone, string> = Object.fromEntries(
  ZONES.map((z) => [z.zone, z.label]),
) as Record<Zone, string>

export const EVIDENCE_LABEL = {
  solide: 'solide',
  partielle: 'partielle',
  'non-demontree': 'non démontrée',
} as const
