/**
 * Generates db/002_seed_content.sql from the JSON in src/content, so the seeded
 * database and the offline fallback are provably the same content (§12).
 *
 * Run with: pnpm gen:seed  (also invoked by pnpm test's pretest, see below)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')

interface Step {
  position: number
  name: string
  durationS: number
  cue: string
  figureKey: string
}
interface Routine {
  slug: string
  title: string
  zone: string
  durationS: number
  summary: string
  accent: string
  sortOrder: number
  steps: Step[]
}
interface Article {
  slug: string
  title: string
  dek: string
  bodyMd: string
  tag: string
  evidence: string
  readMin: number
  sourceLabel: string
  sourceUrl: string
  sortOrder: number
}

const routines: Routine[] = JSON.parse(
  readFileSync(resolve(root, 'src/content/routines.json'), 'utf8'),
)
const articles: Article[] = JSON.parse(
  readFileSync(resolve(root, 'src/content/articles.json'), 'utf8'),
)

/** Single-quote a SQL string literal, doubling embedded quotes. */
function q(s: string): string {
  return `'${s.replace(/'/g, "''")}'`
}

const lines: string[] = []
lines.push('-- Relève — seed content (§12). GENERATED by scripts/gen-seed.ts.')
lines.push('-- Do not edit by hand: edit src/content/*.json and re-run `pnpm gen:seed`.')
lines.push('-- Idempotent: safe to re-run. Content is authoritative and fully replaced.')
lines.push('')
lines.push('BEGIN;')
lines.push('')
lines.push('-- Wipe seeded content (routine_steps cascade from routines).')
lines.push('TRUNCATE routines RESTART IDENTITY CASCADE;')
lines.push('TRUNCATE articles RESTART IDENTITY CASCADE;')
lines.push('')

for (const r of routines) {
  lines.push(`-- ${r.slug}`)
  lines.push('WITH r AS (')
  lines.push('  INSERT INTO routines (slug, title, zone, duration_s, summary, accent, sort_order)')
  lines.push(
    `  VALUES (${q(r.slug)}, ${q(r.title)}, ${q(r.zone)}, ${r.durationS}, ${q(r.summary)}, ${q(
      r.accent,
    )}, ${r.sortOrder})`,
  )
  lines.push('  RETURNING id')
  lines.push(')')
  lines.push('INSERT INTO routine_steps (routine_id, position, name, duration_s, cue, figure_key)')
  lines.push('VALUES')
  lines.push(
    r.steps
      .map(
        (s) =>
          `  ((SELECT id FROM r), ${s.position}, ${q(s.name)}, ${s.durationS}, ${q(s.cue)}, ${q(
            s.figureKey,
          )})`,
      )
      .join(',\n') + ';',
  )
  lines.push('')
}

for (const a of articles) {
  lines.push(`-- ${a.slug}`)
  lines.push(
    'INSERT INTO articles (slug, title, dek, body_md, tag, evidence, read_min, source_label, source_url, sort_order)',
  )
  lines.push(
    `VALUES (${q(a.slug)}, ${q(a.title)}, ${q(a.dek)}, ${q(a.bodyMd)}, ${q(a.tag)}, ${q(
      a.evidence,
    )}, ${a.readMin}, ${q(a.sourceLabel)}, ${q(a.sourceUrl)}, ${a.sortOrder});`,
  )
  lines.push('')
}

lines.push('COMMIT;')
lines.push('')

writeFileSync(resolve(root, 'db/002_seed_content.sql'), lines.join('\n'))
console.log(
  `db/002_seed_content.sql written: ${routines.length} routines, ${articles.length} articles`,
)
