/**
 * Generates db/002_seed_content.sql from the JSON in src/content, so the seeded
 * database and the offline fallback are provably the same content (§12).
 *
 * Run with: pnpm gen:seed  (also invoked by pnpm test's pretest, see below)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')

interface Step {
  position: number
  name: string
  durationS: number
  cue: string
  figureKey: string
  exerciseKey: string
}
interface Exercise {
  title: string
  steps: string[]
  tips: string[]
  easier: string
  muscles: string[]
  avoid: string
}
interface Routine {
  slug: string
  title: string
  zone: string
  durationS: number
  summary: string
  accent: string
  sortOrder: number
  steps: Step[]
}
interface Article {
  slug: string
  title: string
  dek: string
  bodyMd: string
  tag: string
  evidence: string
  readMin: number
  sourceLabel: string
  sourceUrl: string
  sortOrder: number
}

const routines: Routine[] = JSON.parse(
  readFileSync(resolve(root, 'src/content/routines.json'), 'utf8'),
)
const articles: Article[] = JSON.parse(
  readFileSync(resolve(root, 'src/content/articles.json'), 'utf8'),
)
const exercises: Record<string, Exercise> = JSON.parse(
  readFileSync(resolve(root, 'src/content/exercises.json'), 'utf8'),
)

/** Single-quote a SQL string literal, doubling embedded quotes. */
function q(s: string): string {
  return `'${s.replace(/'/g, "''")}'`
}

/** `ARRAY['a', 'b']`, quoted the same way as a single string. */
function qArray(items: string[]): string {
  return `ARRAY[${items.map(q).join(', ')}]`
}

/** `slug <> ALL (ARRAY['a', 'b'])` — the slugs the JSON no longer defines. */
function keepList(slugs: string[]): string {
  return `ARRAY[${slugs.map(q).join(', ')}]`
}

const lines: string[] = []
lines.push('-- Log Off — seed content (§12). GENERATED by scripts/gen-seed.ts.')
lines.push('-- Do not edit by hand: edit src/content/*.json and re-run `pnpm gen:seed`.')
lines.push('-- Idempotent: safe to re-run. Content is authoritative and fully replaced.')
lines.push('--')
lines.push('-- Upsert on slug rather than TRUNCATE: `TRUNCATE routines CASCADE` also empties')
lines.push('-- every table with a foreign key to it, ignoring the ON DELETE action, and')
lines.push('-- completions.routine_id references routines(id) — re-seeding used to wipe the')
lines.push('-- completion history of every user. Upserting keeps routine ids stable, so a')
lines.push('-- completion stays attached to the routine it was done for.')
lines.push('--')
lines.push('-- Never put an ASCII apostrophe in these comments: the statement splitter in')
lines.push('-- scripts/migrate.ts does not skip -- comments and would read it as a string.')
lines.push('')
lines.push('BEGIN;')
lines.push('')

// Exercises first: routine_steps.exercise_key references them, so the rows
// they point at must already exist by the time a step is inserted.
for (const [key, ex] of Object.entries(exercises)) {
  lines.push(`-- ${key}`)
  lines.push('INSERT INTO exercises (key, title, steps, tips, easier, muscles, avoid)')
  lines.push(
    `VALUES (${q(key)}, ${q(ex.title)}, ${qArray(ex.steps)}, ${qArray(ex.tips)}, ${q(
      ex.easier,
    )}, ${qArray(ex.muscles)}, ${q(ex.avoid)})`,
  )
  lines.push('ON CONFLICT (key) DO UPDATE SET')
  lines.push('  title = EXCLUDED.title, steps = EXCLUDED.steps, tips = EXCLUDED.tips,')
  lines.push('  easier = EXCLUDED.easier, muscles = EXCLUDED.muscles, avoid = EXCLUDED.avoid;')
}
lines.push('')

for (const r of routines) {
  lines.push(`-- ${r.slug}`)
  lines.push('INSERT INTO routines (slug, title, zone, duration_s, summary, accent, sort_order)')
  lines.push(
    `VALUES (${q(r.slug)}, ${q(r.title)}, ${q(r.zone)}, ${r.durationS}, ${q(r.summary)}, ${q(
      r.accent,
    )}, ${r.sortOrder})`,
  )
  lines.push('ON CONFLICT (slug) DO UPDATE SET')
  lines.push('  title = EXCLUDED.title, zone = EXCLUDED.zone, duration_s = EXCLUDED.duration_s,')
  lines.push(
    '  summary = EXCLUDED.summary, accent = EXCLUDED.accent, sort_order = EXCLUDED.sort_order;',
  )
  // Separate statements, not data-modifying CTEs: inside one statement the
  // delete and the insert would race on the (routine_id, position) unique index.
  lines.push(
    `DELETE FROM routine_steps WHERE routine_id = (SELECT id FROM routines WHERE slug = ${q(
      r.slug,
    )});`,
  )
  lines.push(
    'INSERT INTO routine_steps (routine_id, position, name, duration_s, cue, figure_key, exercise_key)',
  )
  lines.push('VALUES')
  lines.push(
    r.steps
      .map(
        (s) =>
          `  ((SELECT id FROM routines WHERE slug = ${q(r.slug)}), ${s.position}, ${q(s.name)}, ${
            s.durationS
          }, ${q(s.cue)}, ${q(s.figureKey)}, ${q(s.exerciseKey)})`,
      )
      .join(',\n') + ';',
  )
  lines.push('')
}

for (const a of articles) {
  lines.push(`-- ${a.slug}`)
  lines.push(
    'INSERT INTO articles (slug, title, dek, body_md, tag, evidence, read_min, source_label, source_url, sort_order)',
  )
  lines.push(
    `VALUES (${q(a.slug)}, ${q(a.title)}, ${q(a.dek)}, ${q(a.bodyMd)}, ${q(a.tag)}, ${q(
      a.evidence,
    )}, ${a.readMin}, ${q(a.sourceLabel)}, ${q(a.sourceUrl)}, ${a.sortOrder})`,
  )
  lines.push('ON CONFLICT (slug) DO UPDATE SET')
  lines.push('  title = EXCLUDED.title, dek = EXCLUDED.dek, body_md = EXCLUDED.body_md,')
  lines.push('  tag = EXCLUDED.tag, evidence = EXCLUDED.evidence, read_min = EXCLUDED.read_min,')
  lines.push('  source_label = EXCLUDED.source_label, source_url = EXCLUDED.source_url,')
  lines.push('  sort_order = EXCLUDED.sort_order;')
  lines.push('')
}

lines.push('-- Drop content the JSON no longer defines. Deleting a routine sets')
lines.push('-- completions.routine_id to NULL (ON DELETE SET NULL); the rows survive.')
lines.push(`DELETE FROM routines WHERE slug <> ALL (${keepList(routines.map((r) => r.slug))});`)
lines.push(`DELETE FROM articles WHERE slug <> ALL (${keepList(articles.map((a) => a.slug))});`)
// Last, and only after routines/steps above have dropped their own stale rows
// (cascading through routine_steps): nothing still points at an exercise this
// deletes, or the FK would refuse it.
lines.push(
  `DELETE FROM exercises WHERE key <> ALL (${keepList(Object.keys(exercises))});`,
)
lines.push('')
lines.push('COMMIT;')
lines.push('')

writeFileSync(resolve(root, 'db/002_seed_content.sql'), lines.join('\n'))
console.log(
  `db/002_seed_content.sql written: ${routines.length} routines, ${articles.length} articles, ` +
    `${Object.keys(exercises).length} exercises`,
)
