import { describe, expect, it } from 'vitest'
import { readFileSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { statements } from './sql-split.ts'

/**
 * The splitter had no test, and the bug it shipped could only be seen against a
 * live database: a semicolon inside a `--` comment cut a migration in the
 * middle of a sentence, and Postgres was handed « the rows survive. » as a
 * statement. `db/002_seed_content.sql` carried exactly that, generated into it.
 *
 * The last test below is the one that matters: it runs the real migrations
 * through the real splitter and insists every piece looks like SQL.
 */

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

describe('statements', () => {
  it('splits on unquoted semicolons', () => {
    expect(statements('SELECT 1; SELECT 2;')).toEqual(['SELECT 1', 'SELECT 2'])
  })

  it('drops trailing whitespace and empty pieces', () => {
    expect(statements('SELECT 1;;\n\n  ;')).toEqual(['SELECT 1'])
  })

  it('leaves a semicolon inside a string literal alone', () => {
    expect(statements("INSERT INTO t VALUES ('a; b');")).toEqual([
      "INSERT INTO t VALUES ('a; b')",
    ])
  })

  it('handles a doubled quote inside a literal', () => {
    expect(statements("INSERT INTO t VALUES ('l''app; ici');")).toEqual([
      "INSERT INTO t VALUES ('l''app; ici')",
    ])
  })

  it('does not split on a semicolon inside a comment', () => {
    // The bug, in one line.
    const sql = '-- generated by gen-seed.ts ; and then\nDELETE FROM t;'
    expect(statements(sql)).toEqual(['DELETE FROM t'])
  })

  it('does not open a string on an apostrophe inside a comment', () => {
    // The hazard the old code could only warn future authors about.
    const sql = "-- ce fichier n'est pas edite a la main\nSELECT 1;\nSELECT 2;"
    expect(statements(sql)).toEqual(['SELECT 1', 'SELECT 2'])
  })

  it('keeps a double dash that is part of a string', () => {
    const sql = "INSERT INTO a VALUES ('deux tirets -- ici');"
    expect(statements(sql)).toEqual(["INSERT INTO a VALUES ('deux tirets -- ici')"])
  })

  it('keeps the newline that ends a comment, so the next statement stands alone', () => {
    expect(statements('-- note\nSELECT 1;')).toEqual(['SELECT 1'])
  })

  it('leaves a dollar-quoted body whole', () => {
    const sql = "DO $$ BEGIN PERFORM 'a; b'; END $$;"
    expect(statements(sql)).toHaveLength(1)
  })

  it('cuts every shipped migration into something that looks like SQL', () => {
    const dir = resolve(root, 'db')
    const files = readdirSync(dir).filter((f) => /^\d{3}_.*\.sql$/.test(f))
    expect(files.length).toBeGreaterThan(0)
    const looksLikeSql =
      /^(BEGIN|COMMIT|ALTER|CREATE|INSERT|DELETE|UPDATE|SELECT|DROP|COMMENT|SET|GRANT|REVOKE|DO|WITH)\b/i
    for (const file of files) {
      for (const stmt of statements(readFileSync(resolve(dir, file), 'utf8'))) {
        expect(looksLikeSql.test(stmt), `${file}: « ${stmt.slice(0, 60)}… »`).toBe(true)
      }
    }
  })
})
